### ISSUE TITLE
Not being installed from package.json

### ISSUE THREAD

**Issue by jacobthemyth** [mikeedwards/process-env-brunch#6]
I have process-env-brunch in my dependencies section of package.json, but when I run `npm install` with no arguments, process-env-brunch isn't installed. If I manually type `npm install process-env-brunch`, everything works fine though. If I add `--save`, I get the line `"process-env-brunch": "~1.4.4-d"` added to my dependencies, but then if I `rm -rf node_modules && npm install`, again, process-env-brunch is not installed. I tried updating the node versions in `engines` in package.json to include 0.10 (I'm on 0.10.26), but that didn't seem to work either. Do you have any ideas on how to get it to work automatically with `npm install`? Thanks.

**Comment by gfrivolt** [comment]
Works for me. Using node v6.5.0, npm v3.10.3

**Comment by mikeedwards** [comment]
@gfrivolt Good to know. Unless there are any objections, I'll close this issue.
